#!/usr/bin/env python3
"""Render out/classified.json into a static HTML preview page.

This is a DETERMINISTIC preview (no LLM) so you can eyeball the day's bucketed
papers and page layout before the Claude Code agent writes the polished prose
briefing. Buckets are shown in classify.py order; empty buckets are skipped.

Usage:
    python scripts/build_preview.py                 # reads out/classified.json -> out/preview.html
    python scripts/build_preview.py in.json out.html
"""
from __future__ import annotations

import html as htmllib
import json
import sys
from datetime import date


def esc(s) -> str:
    return htmllib.escape(str(s), quote=False)


def paper_link(p: dict) -> str:
    if p.get("source") == "crossref":
        return p.get("url") or (f"https://doi.org/{p.get('doi')}" if p.get("doi") else "#")
    aid = p.get("arxiv_id")
    return f"https://arxiv.org/abs/{aid}" if aid else "#"


def authors_str(p: dict) -> str:
    a = p.get("authors") or []
    if not a:
        return ""
    return a[0] + (f" 외 {len(a) - 1}명" if len(a) > 1 else "")


def meta_str(p: dict) -> str:
    if p.get("source") == "crossref":
        bits = [p.get("journal", "")]
        if p.get("created"):
            bits.append(f"등록 {p['created']}")
        return " · ".join(b for b in bits if b)
    abs = (p.get("abstract") or "").strip()
    return abs[:200] + ("…" if len(abs) > 200 else "")


CSS = """
*{box-sizing:border-box}
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans KR","Apple SD Gothic Neo",sans-serif;
background:#f6f7f9;color:#1f2328;line-height:1.7;font-size:15px;padding:28px 16px;word-break:keep-all}
.container{max-width:960px;margin:0 auto;background:#fff;border-radius:12px;
box-shadow:0 1px 3px rgba(0,0,0,.06);padding:32px 40px 48px}
h1{font-size:25px;margin:0 0 4px;color:#0d1117}
.sub{color:#656d76;font-size:13.5px;margin:0 0 8px}
.banner{background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:10px 14px;margin:14px 0 26px;
font-size:13px;color:#7c2d12}
h2{font-size:18px;margin:30px 0 6px;padding-bottom:6px;border-bottom:2px solid #e5e7eb;color:#0d1117}
h2 .n{font-size:13px;color:#656d76;font-weight:400;margin-left:6px}
.paper{padding:10px 0;border-top:1px solid #f0f1f3}
.paper:first-of-type{border-top:none}
.paper a{color:#0969da;text-decoration:none;font-weight:600}
.paper a:hover{text-decoration:underline}
.badge{display:inline-block;font-size:10.5px;font-weight:700;padding:1px 6px;border-radius:9px;
background:#eef2ff;color:#3730a3;border:1px solid #c7d2fe;margin-left:6px;vertical-align:middle}
.badge.jnl{background:#fef3c7;color:#854d0e;border-color:#fde68a}
.who{color:#475569;font-size:12.5px;margin:2px 0 0}
.meta{color:#586069;font-size:12.5px;margin:3px 0 0}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;color:#656d76;font-size:12.5px}
"""


def render(data: dict, today: str) -> str:
    cats = " · ".join(data.get("categories") or [])
    parts = [
        "<!DOCTYPE html><html lang=ko><head><meta charset=UTF-8>",
        "<meta name=viewport content='width=device-width,initial-scale=1'>",
        f"<title>Daily Preview — {esc(today)}</title><style>{CSS}</style></head><body><div class=container>",
        f"<h1>🔬 Daily Briefing Preview</h1>",
        f"<p class=sub>{esc(today)} · 추적 {esc(cats)}</p>",
        f"<p class=sub>전체 {data.get('total', 0)}건 dedup · 버킷 배정 {data.get('selected', 0)}건</p>",
        "<div class=banner>⚠️ 결정론적 미리보기입니다(LLM 미사용). 실제 발행본은 Claude Code 에이전트가 런북대로 작성한 자연어 브리핑입니다.</div>",
    ]
    for bucket, info in (data.get("buckets") or {}).items():
        papers = info.get("papers") or []
        if not papers:
            continue
        badges = " ".join(f"{k}:{v}" for k, v in sorted((info.get("by_badge") or {}).items()))
        parts.append(f"<h2>{esc(bucket)}<span class=n>{info.get('total', len(papers))}편 · {esc(badges)}</span></h2>")
        for p in papers:
            is_jnl = p.get("source") == "crossref"
            badge_cls = "badge jnl" if is_jnl else "badge"
            parts.append('<div class=paper>')
            parts.append(
                f'<a href="{esc(paper_link(p))}" target=_blank>{esc(p.get("title", "(제목 없음)"))}</a>'
                f'<span class="{badge_cls}">{esc(p.get("badge", "?"))}</span>'
            )
            who = authors_str(p)
            if who:
                parts.append(f'<div class=who>{esc(who)}</div>')
            meta = meta_str(p)
            if meta:
                parts.append(f'<div class=meta>{esc(meta)}</div>')
            parts.append('</div>')
    parts.append(
        f'<div class=footer>Generated by scripts/build_preview.py from out/classified.json · '
        f'arXiv /new(replacements 제외) + Crossref created-date 최근 7일</div>'
    )
    parts.append("</div></body></html>")
    return "\n".join(parts)


def main() -> int:
    in_path = sys.argv[1] if len(sys.argv) > 1 else "out/classified.json"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "out/preview.html"
    with open(in_path, encoding="utf-8") as f:
        data = json.load(f)
    today = date.today().isoformat()
    doc = render(data, today)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)
    print(f"WROTE {out_path} ({len(doc)} bytes) — open it in a browser to preview")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
